-- Seasonal events and national holidays (generated by db/events/build-migration.mjs).

-- Halloween: Haunted Latvia
INSERT INTO collections (slug, title, description, icon, kind, country, xp_reward, starts_at, ends_at, status, sort, i18n)
VALUES ('halloween-2026', 'Halloween: Haunted Latvia', 'Castle ruins, fortresses and ghost legends. Limited edition until 2 November.', '', 'seasonal', 'LV', 600, '2026-10-24 00:00 Europe/Riga'::timestamptz, '2026-11-03 00:00 Europe/Riga'::timestamptz, 'published', 2,
        '{"lv":{"title":"Helovīni: spoku Latvija","description":"Pilsdrupas, cietokšņi un spoku leģendas. Ierobežots laiks: līdz 2. novembrim."},"ru":{"title":"Хэллоуин: Латвия с привидениями","description":"Руины замков, крепости и легенды о призраках. Только до 2 ноября."}}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'halloween-2026-koknese-castle', 'Halloween: ' || p.name, 'Visit this spooky spot during Halloween week.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-10-24 00:00 Europe/Riga'::timestamptz, '2026-11-03 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Helovīni: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē šo baiso vietu Helovīnu nedēļā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Хэллоуин: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите это жуткое место во время недели Хэллоуина.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'koknese-castle'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 1 FROM collections c, challenges ch WHERE c.slug = 'halloween-2026' AND ch.slug = 'halloween-2026-koknese-castle'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'halloween-2026-daugavpils-fortress', 'Halloween: ' || p.name, 'Visit this spooky spot during Halloween week.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-10-24 00:00 Europe/Riga'::timestamptz, '2026-11-03 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Helovīni: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē šo baiso vietu Helovīnu nedēļā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Хэллоуин: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите это жуткое место во время недели Хэллоуина.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'daugavpils-fortress'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 2 FROM collections c, challenges ch WHERE c.slug = 'halloween-2026' AND ch.slug = 'halloween-2026-daugavpils-fortress'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'halloween-2026-karosta-north-pier', 'Halloween: ' || p.name, 'Visit this spooky spot during Halloween week.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-10-24 00:00 Europe/Riga'::timestamptz, '2026-11-03 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Helovīni: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē šo baiso vietu Helovīnu nedēļā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Хэллоуин: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите это жуткое место во время недели Хэллоуина.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'karosta-north-pier'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 3 FROM collections c, challenges ch WHERE c.slug = 'halloween-2026' AND ch.slug = 'halloween-2026-karosta-north-pier'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'halloween-2026-bauska-castle', 'Halloween: ' || p.name, 'Visit this spooky spot during Halloween week.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-10-24 00:00 Europe/Riga'::timestamptz, '2026-11-03 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Helovīni: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē šo baiso vietu Helovīnu nedēļā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Хэллоуин: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите это жуткое место во время недели Хэллоуина.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'bauska-castle'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 4 FROM collections c, challenges ch WHERE c.slug = 'halloween-2026' AND ch.slug = 'halloween-2026-bauska-castle'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'halloween-2026-sigulda-castle', 'Halloween: ' || p.name, 'Visit this spooky spot during Halloween week.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-10-24 00:00 Europe/Riga'::timestamptz, '2026-11-03 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Helovīni: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē šo baiso vietu Helovīnu nedēļā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Хэллоуин: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите это жуткое место во время недели Хэллоуина.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'sigulda-castle'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 5 FROM collections c, challenges ch WHERE c.slug = 'halloween-2026' AND ch.slug = 'halloween-2026-sigulda-castle'
ON CONFLICT DO NOTHING;
INSERT INTO achievements (id, title, description, icon, rule, xp_reward, is_hidden, sort, i18n)
VALUES ('halloween-2026', 'Ghost Hunter 2026', 'Complete the Halloween event in 2026.', '', '{"type":"collection_completed","collection":"halloween-2026"}'::jsonb, 250, true, 100 + 2,
        '{"lv":{"title":"Spoku mednieks 2026","description":"Pabeidz Helovīnu notikumu 2026. gadā."},"ru":{"title":"Охотник за привидениями 2026","description":"Завершите событие Хэллоуина в 2026 году."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Latvia's November
INSERT INTO collections (slug, title, description, icon, kind, country, xp_reward, starts_at, ends_at, status, sort, i18n)
VALUES ('latvia-november-2026', 'Latvia''s November', 'Lāčplēsis Day on 11 November and the 108th birthday of Latvia on 18 November. Visit the places of freedom.', '', 'seasonal', 'LV', 750, '2026-11-09 00:00 Europe/Riga'::timestamptz, '2026-11-23 00:00 Europe/Riga'::timestamptz, 'published', 3,
        '{"lv":{"title":"Latvijas novembris","description":"Lāčplēša diena 11. novembrī un Latvijas 108. dzimšanas diena 18. novembrī. Apmeklē brīvības vietas."},"ru":{"title":"Ноябрь Латвии","description":"День Лачплесиса 11 ноября и 108-й день рождения Латвии 18 ноября. Посетите места свободы."}}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'latvia-november-2026-freedom-monument', 'Latvia''s November: ' || p.name, 'Visit during the November national holidays.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-11-09 00:00 Europe/Riga'::timestamptz, '2026-11-23 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Latvijas novembris: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē novembra valsts svētkos.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Ноябрь Латвии: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время ноябрьских государственных праздников.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'freedom-monument'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 1 FROM collections c, challenges ch WHERE c.slug = 'latvia-november-2026' AND ch.slug = 'latvia-november-2026-freedom-monument'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'latvia-november-2026-national-library-lv', 'Latvia''s November: ' || p.name, 'Visit during the November national holidays.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-11-09 00:00 Europe/Riga'::timestamptz, '2026-11-23 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Latvijas novembris: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē novembra valsts svētkos.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Ноябрь Латвии: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время ноябрьских государственных праздников.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'national-library-lv'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 2 FROM collections c, challenges ch WHERE c.slug = 'latvia-november-2026' AND ch.slug = 'latvia-november-2026-national-library-lv'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'latvia-november-2026-cesis-old-town', 'Latvia''s November: ' || p.name, 'Visit during the November national holidays.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-11-09 00:00 Europe/Riga'::timestamptz, '2026-11-23 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Latvijas novembris: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē novembra valsts svētkos.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Ноябрь Латвии: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время ноябрьских государственных праздников.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'cesis-old-town'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 3 FROM collections c, challenges ch WHERE c.slug = 'latvia-november-2026' AND ch.slug = 'latvia-november-2026-cesis-old-town'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'latvia-november-2026-riga-cathedral', 'Latvia''s November: ' || p.name, 'Visit during the November national holidays.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-11-09 00:00 Europe/Riga'::timestamptz, '2026-11-23 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Latvijas novembris: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē novembra valsts svētkos.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Ноябрь Латвии: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время ноябрьских государственных праздников.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'riga-cathedral'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 4 FROM collections c, challenges ch WHERE c.slug = 'latvia-november-2026' AND ch.slug = 'latvia-november-2026-riga-cathedral'
ON CONFLICT DO NOTHING;
INSERT INTO achievements (id, title, description, icon, rule, xp_reward, is_hidden, sort, i18n)
VALUES ('latvia-november-2026', 'Latvia 108', 'Complete the Latvia''s November event in 2026.', '', '{"type":"collection_completed","collection":"latvia-november-2026"}'::jsonb, 300, true, 100 + 3,
        '{"lv":{"title":"Latvijai 108","description":"Pabeidz notikumu “Latvijas novembris” 2026. gadā."},"ru":{"title":"Латвии 108","description":"Завершите событие «Ноябрь Латвии» в 2026 году."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Christmas in Latvia
INSERT INTO collections (slug, title, description, icon, kind, country, xp_reward, starts_at, ends_at, status, sort, i18n)
VALUES ('christmas-2026', 'Christmas in Latvia', 'Christmas markets, lights and the city where the first decorated Christmas tree was set up in 1510.', '', 'seasonal', 'LV', 750, '2026-12-01 00:00 Europe/Riga'::timestamptz, '2027-01-07 00:00 Europe/Riga'::timestamptz, 'published', 4,
        '{"lv":{"title":"Ziemassvētki Latvijā","description":"Ziemassvētku tirdziņi, gaismas un pilsēta, kur 1510. gadā rotāja pirmo Ziemassvētku egli."},"ru":{"title":"Рождество в Латвии","description":"Рождественские ярмарки, огни и город, где в 1510 году нарядили первую рождественскую ёлку."}}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'christmas-2026-riga-old-town', 'Christmas: ' || p.name, 'Visit during the Christmas season.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-12-01 00:00 Europe/Riga'::timestamptz, '2027-01-07 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Ziemassvētki: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Ziemassvētku laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Рождество: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите в рождественский сезон.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'riga-old-town'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 1 FROM collections c, challenges ch WHERE c.slug = 'christmas-2026' AND ch.slug = 'christmas-2026-riga-old-town'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'christmas-2026-house-of-blackheads', 'Christmas: ' || p.name, 'Visit during the Christmas season.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-12-01 00:00 Europe/Riga'::timestamptz, '2027-01-07 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Ziemassvētki: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Ziemassvētku laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Рождество: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите в рождественский сезон.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'house-of-blackheads'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 2 FROM collections c, challenges ch WHERE c.slug = 'christmas-2026' AND ch.slug = 'christmas-2026-house-of-blackheads'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'christmas-2026-riga-cathedral', 'Christmas: ' || p.name, 'Visit during the Christmas season.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-12-01 00:00 Europe/Riga'::timestamptz, '2027-01-07 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Ziemassvētki: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Ziemassvētku laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Рождество: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите в рождественский сезон.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'riga-cathedral'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 3 FROM collections c, challenges ch WHERE c.slug = 'christmas-2026' AND ch.slug = 'christmas-2026-riga-cathedral'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'christmas-2026-cesis-old-town', 'Christmas: ' || p.name, 'Visit during the Christmas season.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-12-01 00:00 Europe/Riga'::timestamptz, '2027-01-07 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Ziemassvētki: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Ziemassvētku laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Рождество: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите в рождественский сезон.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'cesis-old-town'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 4 FROM collections c, challenges ch WHERE c.slug = 'christmas-2026' AND ch.slug = 'christmas-2026-cesis-old-town'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'christmas-2026-kuldiga-old-town', 'Christmas: ' || p.name, 'Visit during the Christmas season.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2026-12-01 00:00 Europe/Riga'::timestamptz, '2027-01-07 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Ziemassvētki: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Ziemassvētku laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Рождество: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите в рождественский сезон.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'kuldiga-old-town'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 5 FROM collections c, challenges ch WHERE c.slug = 'christmas-2026' AND ch.slug = 'christmas-2026-kuldiga-old-town'
ON CONFLICT DO NOTHING;
INSERT INTO achievements (id, title, description, icon, rule, xp_reward, is_hidden, sort, i18n)
VALUES ('christmas-2026', 'Christmas Explorer 2026', 'Complete the Christmas event in 2026.', '', '{"type":"collection_completed","collection":"christmas-2026"}'::jsonb, 300, true, 100 + 4,
        '{"lv":{"title":"Ziemassvētku pētnieks 2026","description":"Pabeidz Ziemassvētku notikumu 2026. gadā."},"ru":{"title":"Рождественский исследователь 2026","description":"Завершите рождественское событие 2026 года."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- White Winter
INSERT INTO collections (slug, title, description, icon, kind, country, xp_reward, starts_at, ends_at, status, sort, i18n)
VALUES ('winter-2027', 'White Winter', 'Frozen waterfalls, snowy bogs and the winter sea.', '', 'seasonal', 'LV', 600, '2027-01-08 00:00 Europe/Riga'::timestamptz, '2027-03-01 00:00 Europe/Riga'::timestamptz, 'published', 5,
        '{"lv":{"title":"Baltā ziema","description":"Aizsaluši ūdenskritumi, sniegoti purvi un ziemas jūra."},"ru":{"title":"Белая зима","description":"Замёрзшие водопады, заснеженные болота и зимнее море."}}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'winter-2027-sigulda-castle', 'White Winter: ' || p.name, 'Visit in winter.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-01-08 00:00 Europe/Riga'::timestamptz, '2027-03-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Baltā ziema: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē ziemā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Белая зима: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите зимой.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'sigulda-castle'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 1 FROM collections c, challenges ch WHERE c.slug = 'winter-2027' AND ch.slug = 'winter-2027-sigulda-castle'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'winter-2027-kemeri-bog', 'White Winter: ' || p.name, 'Visit in winter.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-01-08 00:00 Europe/Riga'::timestamptz, '2027-03-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Baltā ziema: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē ziemā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Белая зима: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите зимой.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'kemeri-bog'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 2 FROM collections c, challenges ch WHERE c.slug = 'winter-2027' AND ch.slug = 'winter-2027-kemeri-bog'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'winter-2027-cape-kolka', 'White Winter: ' || p.name, 'Visit in winter.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-01-08 00:00 Europe/Riga'::timestamptz, '2027-03-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Baltā ziema: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē ziemā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Белая зима: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите зимой.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'cape-kolka'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 3 FROM collections c, challenges ch WHERE c.slug = 'winter-2027' AND ch.slug = 'winter-2027-cape-kolka'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'winter-2027-venta-rapid', 'White Winter: ' || p.name, 'Visit in winter.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-01-08 00:00 Europe/Riga'::timestamptz, '2027-03-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Baltā ziema: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē ziemā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Белая зима: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите зимой.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'venta-rapid'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 4 FROM collections c, challenges ch WHERE c.slug = 'winter-2027' AND ch.slug = 'winter-2027-venta-rapid'
ON CONFLICT DO NOTHING;
INSERT INTO achievements (id, title, description, icon, rule, xp_reward, is_hidden, sort, i18n)
VALUES ('winter-2027', 'Winter Explorer 2027', 'Complete the White Winter event in 2027.', '', '{"type":"collection_completed","collection":"winter-2027"}'::jsonb, 250, true, 100 + 5,
        '{"lv":{"title":"Ziemas pētnieks 2027","description":"Pabeidz notikumu “Baltā ziema” 2027. gadā."},"ru":{"title":"Зимний исследователь 2027","description":"Завершите событие «Белая зима» в 2027 году."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Easter in Latvia
INSERT INTO collections (slug, title, description, icon, kind, country, xp_reward, starts_at, ends_at, status, sort, i18n)
VALUES ('easter-2027', 'Easter in Latvia', 'Churches, bells and the first spring sun. Easter Sunday is 28 March 2027.', '', 'seasonal', 'LV', 500, '2027-03-22 00:00 Europe/Riga'::timestamptz, '2027-04-06 00:00 Europe/Riga'::timestamptz, 'published', 6,
        '{"lv":{"title":"Lieldienas Latvijā","description":"Baznīcas, zvani un pirmā pavasara saule. Lieldienas ir 2027. gada 28. martā."},"ru":{"title":"Пасха в Латвии","description":"Храмы, колокола и первое весеннее солнце. Пасха — 28 марта 2027 года."}}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'easter-2027-aglona-basilica', 'Easter: ' || p.name, 'Visit during the Easter holidays.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-03-22 00:00 Europe/Riga'::timestamptz, '2027-04-06 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Lieldienas: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Lieldienu brīvdienās.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Пасха: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время пасхальных праздников.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'aglona-basilica'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 1 FROM collections c, challenges ch WHERE c.slug = 'easter-2027' AND ch.slug = 'easter-2027-aglona-basilica'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'easter-2027-riga-cathedral', 'Easter: ' || p.name, 'Visit during the Easter holidays.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-03-22 00:00 Europe/Riga'::timestamptz, '2027-04-06 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Lieldienas: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Lieldienu brīvdienās.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Пасха: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время пасхальных праздников.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'riga-cathedral'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 2 FROM collections c, challenges ch WHERE c.slug = 'easter-2027' AND ch.slug = 'easter-2027-riga-cathedral'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'easter-2027-st-peters-riga', 'Easter: ' || p.name, 'Visit during the Easter holidays.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-03-22 00:00 Europe/Riga'::timestamptz, '2027-04-06 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Lieldienas: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Lieldienu brīvdienās.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Пасха: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время пасхальных праздников.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'st-peters-riga'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 3 FROM collections c, challenges ch WHERE c.slug = 'easter-2027' AND ch.slug = 'easter-2027-st-peters-riga'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'easter-2027-rundale-palace', 'Easter: ' || p.name, 'Visit during the Easter holidays.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-03-22 00:00 Europe/Riga'::timestamptz, '2027-04-06 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Lieldienas: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Lieldienu brīvdienās.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Пасха: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время пасхальных праздников.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'rundale-palace'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 4 FROM collections c, challenges ch WHERE c.slug = 'easter-2027' AND ch.slug = 'easter-2027-rundale-palace'
ON CONFLICT DO NOTHING;
INSERT INTO achievements (id, title, description, icon, rule, xp_reward, is_hidden, sort, i18n)
VALUES ('easter-2027', 'Easter Explorer 2027', 'Complete the Easter event in 2027.', '', '{"type":"collection_completed","collection":"easter-2027"}'::jsonb, 200, true, 100 + 6,
        '{"lv":{"title":"Lieldienu pētnieks 2027","description":"Pabeidz Lieldienu notikumu 2027. gadā."},"ru":{"title":"Пасхальный исследователь 2027","description":"Завершите пасхальное событие 2027 года."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Restoration of Independence
INSERT INTO collections (slug, title, description, icon, kind, country, xp_reward, starts_at, ends_at, status, sort, i18n)
VALUES ('may-4-2027', 'Restoration of Independence', 'On 4 May 1990 Latvia declared its independence restored. Visit the symbols of freedom.', '', 'seasonal', 'LV', 500, '2027-04-30 00:00 Europe/Riga'::timestamptz, '2027-05-06 00:00 Europe/Riga'::timestamptz, 'published', 7,
        '{"lv":{"title":"Neatkarības atjaunošanas diena","description":"1990. gada 4. maijā Latvija atjaunoja neatkarību. Apmeklē brīvības simbolus."},"ru":{"title":"День восстановления независимости","description":"4 мая 1990 года Латвия восстановила независимость. Посетите символы свободы."}}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'may-4-2027-freedom-monument', '4 May: ' || p.name, 'Visit around 4 May.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-04-30 00:00 Europe/Riga'::timestamptz, '2027-05-06 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', '4. maijs: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē ap 4. maiju.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', '4 мая: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите в дни около 4 мая.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'freedom-monument'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 1 FROM collections c, challenges ch WHERE c.slug = 'may-4-2027' AND ch.slug = 'may-4-2027-freedom-monument'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'may-4-2027-national-library-lv', '4 May: ' || p.name, 'Visit around 4 May.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-04-30 00:00 Europe/Riga'::timestamptz, '2027-05-06 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', '4. maijs: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē ap 4. maiju.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', '4 мая: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите в дни около 4 мая.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'national-library-lv'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 2 FROM collections c, challenges ch WHERE c.slug = 'may-4-2027' AND ch.slug = 'may-4-2027-national-library-lv'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'may-4-2027-riga-old-town', '4 May: ' || p.name, 'Visit around 4 May.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-04-30 00:00 Europe/Riga'::timestamptz, '2027-05-06 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', '4. maijs: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē ap 4. maiju.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', '4 мая: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите в дни около 4 мая.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'riga-old-town'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 3 FROM collections c, challenges ch WHERE c.slug = 'may-4-2027' AND ch.slug = 'may-4-2027-riga-old-town'
ON CONFLICT DO NOTHING;
INSERT INTO achievements (id, title, description, icon, rule, xp_reward, is_hidden, sort, i18n)
VALUES ('may-4-2027', '4 May 2027', 'Complete the Restoration of Independence event in 2027.', '', '{"type":"collection_completed","collection":"may-4-2027"}'::jsonb, 200, true, 100 + 7,
        '{"lv":{"title":"4. maijs 2027","description":"Pabeidz Neatkarības atjaunošanas dienas notikumu 2027. gadā."},"ru":{"title":"4 мая 2027","description":"Завершите событие Дня восстановления независимости 2027 года."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Spring Awakening
INSERT INTO collections (slug, title, description, icon, kind, country, xp_reward, starts_at, ends_at, status, sort, i18n)
VALUES ('spring-2027', 'Spring Awakening', 'Flying fish at Ventas Rumba, blossoming gardens and birdsong on the bogs.', '', 'seasonal', 'LV', 600, '2027-04-07 00:00 Europe/Riga'::timestamptz, '2027-06-01 00:00 Europe/Riga'::timestamptz, 'published', 8,
        '{"lv":{"title":"Pavasara mošanās","description":"Lidojošās zivis pie Ventas rumbas, ziedoši dārzi un putnu dziesmas purvos."},"ru":{"title":"Весеннее пробуждение","description":"Летающие рыбы у Вентас румбы, цветущие сады и пение птиц на болотах."}}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'spring-2027-venta-rapid', 'Spring: ' || p.name, 'Visit in spring.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-04-07 00:00 Europe/Riga'::timestamptz, '2027-06-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Pavasaris: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē pavasarī.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Весна: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите весной.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'venta-rapid'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 1 FROM collections c, challenges ch WHERE c.slug = 'spring-2027' AND ch.slug = 'spring-2027-venta-rapid'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'spring-2027-gutmanis-cave', 'Spring: ' || p.name, 'Visit in spring.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-04-07 00:00 Europe/Riga'::timestamptz, '2027-06-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Pavasaris: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē pavasarī.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Весна: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите весной.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'gutmanis-cave'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 2 FROM collections c, challenges ch WHERE c.slug = 'spring-2027' AND ch.slug = 'spring-2027-gutmanis-cave'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'spring-2027-rundale-palace', 'Spring: ' || p.name, 'Visit in spring.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-04-07 00:00 Europe/Riga'::timestamptz, '2027-06-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Pavasaris: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē pavasarī.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Весна: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите весной.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'rundale-palace'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 3 FROM collections c, challenges ch WHERE c.slug = 'spring-2027' AND ch.slug = 'spring-2027-rundale-palace'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'spring-2027-kemeri-bog', 'Spring: ' || p.name, 'Visit in spring.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-04-07 00:00 Europe/Riga'::timestamptz, '2027-06-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Pavasaris: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē pavasarī.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Весна: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите весной.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'kemeri-bog'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 4 FROM collections c, challenges ch WHERE c.slug = 'spring-2027' AND ch.slug = 'spring-2027-kemeri-bog'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'spring-2027-zvartes-iezis', 'Spring: ' || p.name, 'Visit in spring.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-04-07 00:00 Europe/Riga'::timestamptz, '2027-06-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Pavasaris: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē pavasarī.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Весна: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите весной.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'zvartes-iezis'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 5 FROM collections c, challenges ch WHERE c.slug = 'spring-2027' AND ch.slug = 'spring-2027-zvartes-iezis'
ON CONFLICT DO NOTHING;
INSERT INTO achievements (id, title, description, icon, rule, xp_reward, is_hidden, sort, i18n)
VALUES ('spring-2027', 'Spring Explorer 2027', 'Complete the Spring event in 2027.', '', '{"type":"collection_completed","collection":"spring-2027"}'::jsonb, 250, true, 100 + 8,
        '{"lv":{"title":"Pavasara pētnieks 2027","description":"Pabeidz pavasara notikumu 2027. gadā."},"ru":{"title":"Весенний исследователь 2027","description":"Завершите весеннее событие 2027 года."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Jāņi: Midsummer
INSERT INTO collections (slug, title, description, icon, kind, country, xp_reward, starts_at, ends_at, status, sort, i18n)
VALUES ('ligo-2027', 'Jāņi: Midsummer', 'Līgo! Folk song hills, wreaths and the shortest night of the year on 23–24 June.', '', 'seasonal', 'LV', 750, '2027-06-15 00:00 Europe/Riga'::timestamptz, '2027-06-27 00:00 Europe/Riga'::timestamptz, 'published', 9,
        '{"lv":{"title":"Jāņi un Līgo","description":"Līgo! Dainu kalni, vainagi un gada īsākā nakts 23.–24. jūnijā."},"ru":{"title":"Лиго: Янов день","description":"Лиго! Холмы народных песен, венки и самая короткая ночь года 23–24 июня."}}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'ligo-2027-turaida-castle', 'Jāņi: ' || p.name, 'Visit during the Midsummer celebrations.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-15 00:00 Europe/Riga'::timestamptz, '2027-06-27 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Jāņi: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Jāņu laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лиго: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время праздника Лиго.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'turaida-castle'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 1 FROM collections c, challenges ch WHERE c.slug = 'ligo-2027' AND ch.slug = 'ligo-2027-turaida-castle'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'ligo-2027-zvartes-iezis', 'Jāņi: ' || p.name, 'Visit during the Midsummer celebrations.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-15 00:00 Europe/Riga'::timestamptz, '2027-06-27 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Jāņi: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Jāņu laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лиго: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время праздника Лиго.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'zvartes-iezis'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 2 FROM collections c, challenges ch WHERE c.slug = 'ligo-2027' AND ch.slug = 'ligo-2027-zvartes-iezis'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'ligo-2027-cape-kolka', 'Jāņi: ' || p.name, 'Visit during the Midsummer celebrations.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-15 00:00 Europe/Riga'::timestamptz, '2027-06-27 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Jāņi: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Jāņu laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лиго: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время праздника Лиго.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'cape-kolka'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 3 FROM collections c, challenges ch WHERE c.slug = 'ligo-2027' AND ch.slug = 'ligo-2027-cape-kolka'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'ligo-2027-jurmala-beach', 'Jāņi: ' || p.name, 'Visit during the Midsummer celebrations.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-15 00:00 Europe/Riga'::timestamptz, '2027-06-27 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Jāņi: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Jāņu laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лиго: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время праздника Лиго.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'jurmala-beach'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 4 FROM collections c, challenges ch WHERE c.slug = 'ligo-2027' AND ch.slug = 'ligo-2027-jurmala-beach'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'ligo-2027-kuldiga-old-town', 'Jāņi: ' || p.name, 'Visit during the Midsummer celebrations.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-15 00:00 Europe/Riga'::timestamptz, '2027-06-27 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Jāņi: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē Jāņu laikā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лиго: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите во время праздника Лиго.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'kuldiga-old-town'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 5 FROM collections c, challenges ch WHERE c.slug = 'ligo-2027' AND ch.slug = 'ligo-2027-kuldiga-old-town'
ON CONFLICT DO NOTHING;
INSERT INTO achievements (id, title, description, icon, rule, xp_reward, is_hidden, sort, i18n)
VALUES ('ligo-2027', 'Jāņi 2027', 'Complete the Midsummer event in 2027.', '', '{"type":"collection_completed","collection":"ligo-2027"}'::jsonb, 300, true, 100 + 9,
        '{"lv":{"title":"Jāņi 2027","description":"Pabeidz Jāņu notikumu 2027. gadā."},"ru":{"title":"Лиго 2027","description":"Завершите событие Лиго в 2027 году."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Summer by the Sea
INSERT INTO collections (slug, title, description, icon, kind, country, xp_reward, starts_at, ends_at, status, sort, i18n)
VALUES ('summer-2027', 'Summer by the Sea', 'Latvia''s 500 km of coast: beaches, lighthouses and the cape where two seas meet.', '', 'seasonal', 'LV', 700, '2027-06-28 00:00 Europe/Riga'::timestamptz, '2027-09-01 00:00 Europe/Riga'::timestamptz, 'published', 10,
        '{"lv":{"title":"Vasara pie jūras","description":"Latvijas 500 km piekraste: pludmales, bākas un rags, kur satiekas divas jūras."},"ru":{"title":"Лето у моря","description":"500 км побережья Латвии: пляжи, маяки и мыс, где встречаются два моря."}}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'summer-2027-jurmala-beach', 'Summer: ' || p.name, 'Visit in summer.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-28 00:00 Europe/Riga'::timestamptz, '2027-09-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Vasara: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē vasarā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лето: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите летом.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'jurmala-beach'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 1 FROM collections c, challenges ch WHERE c.slug = 'summer-2027' AND ch.slug = 'summer-2027-jurmala-beach'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'summer-2027-liepaja-beach', 'Summer: ' || p.name, 'Visit in summer.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-28 00:00 Europe/Riga'::timestamptz, '2027-09-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Vasara: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē vasarā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лето: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите летом.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'liepaja-beach'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 2 FROM collections c, challenges ch WHERE c.slug = 'summer-2027' AND ch.slug = 'summer-2027-liepaja-beach'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'summer-2027-ventspils-beach', 'Summer: ' || p.name, 'Visit in summer.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-28 00:00 Europe/Riga'::timestamptz, '2027-09-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Vasara: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē vasarā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лето: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите летом.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'ventspils-beach'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 3 FROM collections c, challenges ch WHERE c.slug = 'summer-2027' AND ch.slug = 'summer-2027-ventspils-beach'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'summer-2027-slitere-lighthouse', 'Summer: ' || p.name, 'Visit in summer.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-28 00:00 Europe/Riga'::timestamptz, '2027-09-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Vasara: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē vasarā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лето: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите летом.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'slitere-lighthouse'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 4 FROM collections c, challenges ch WHERE c.slug = 'summer-2027' AND ch.slug = 'summer-2027-slitere-lighthouse'
ON CONFLICT DO NOTHING;
INSERT INTO challenges (slug, title, description, type, category_id, place_id, country, region_id, difficulty, xp_reward,
                        verification, starts_at, ends_at, status, i18n)
SELECT 'summer-2027-cape-kolka', 'Summer: ' || p.name, 'Visit in summer.' || ' ' || p.description || ' Get within ' || p.radius_m || ' m to complete.',
       'seasonal', p.category_id, p.id, p.country, p.region_id, 'casual', 150, 'gps', '2027-06-28 00:00 Europe/Riga'::timestamptz, '2027-09-01 00:00 Europe/Riga'::timestamptz, 'published',
       jsonb_build_object(
         'lv', jsonb_build_object('title', 'Vasara: ' || coalesce(p.i18n->'lv'->>'name', p.name),
               'description', 'Apmeklē vasarā.' || ' ' || coalesce(p.i18n->'lv'->>'description', p.description) || ' Pietuvojies ' || p.radius_m || ' m attālumā, lai izpildītu.'),
         'ru', jsonb_build_object('title', 'Лето: ' || coalesce(p.i18n->'ru'->>'name', p.name),
               'description', 'Посетите летом.' || ' ' || coalesce(p.i18n->'ru'->>'description', p.description) || ' Подойдите ближе чем на ' || p.radius_m || ' м, чтобы выполнить.'))
FROM places p WHERE p.slug = 'cape-kolka'
ON CONFLICT (slug) DO NOTHING;
INSERT INTO collection_items (collection_id, challenge_id, position)
SELECT c.id, ch.id, 5 FROM collections c, challenges ch WHERE c.slug = 'summer-2027' AND ch.slug = 'summer-2027-cape-kolka'
ON CONFLICT DO NOTHING;
INSERT INTO achievements (id, title, description, icon, rule, xp_reward, is_hidden, sort, i18n)
VALUES ('summer-2027', 'Summer Explorer 2027', 'Complete the Summer event in 2027.', '', '{"type":"collection_completed","collection":"summer-2027"}'::jsonb, 250, true, 100 + 10,
        '{"lv":{"title":"Vasaras pētnieks 2027","description":"Pabeidz vasaras notikumu 2027. gadā."},"ru":{"title":"Летний исследователь 2027","description":"Завершите летнее событие 2027 года."}}'::jsonb)
ON CONFLICT (id) DO NOTHING;
